# Generated by Django 3.2 on 2022-02-01 08:58

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the project', max_length=200)),
                ('thumnail_image', models.ImageField(upload_to='project_img-thumnails')),
                ('short_loaction', models.CharField(blank=True, help_text='short loaction:example:uttara/Gulshan etc.', max_length=150, null=True)),
                ('apartment_type', models.TextField(blank=True, help_text='type of apartments -->example:12 storey luxury 4 bedroom apartments', max_length=500, null=True)),
                ('detail_loaction', models.TextField(blank=True, help_text='detail_loactions -->example:House 4A, Road 67,Gulshan', null=True)),
                ('availability', models.CharField(help_text='Sale complete/or not', max_length=200)),
                ('apartment_size', models.IntegerField(help_text='apartment_size in sft', max_length=400)),
                ('handover', models.CharField(blank=True, help_text='handover date ---->:example:December, 2021.', max_length=150, null=True)),
                ('total_apartments', models.IntegerField(help_text='how many apartment--->example:20/10 etc', max_length=400)),
                ('features', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='features of apartment', null=True)),
                ('loaction_map', models.URLField(blank=True, help_text='loaction map url of your project', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projectimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectapp.project')),
            ],
        ),
    ]
