# Generated by Django 3.2 on 2022-02-01 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the project category', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='apartment_size',
            field=models.IntegerField(help_text='apartment_size in sft'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_apartments',
            field=models.IntegerField(help_text='how many apartment--->example:20/10 etc'),
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ForeignKey(blank=True, help_text='name of the project category', null=True, on_delete=django.db.models.deletion.CASCADE, to='projectapp.category'),
        ),
    ]
