# Generated by Django 3.2 on 2022-02-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_auto_20220201_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('ON', 'Ongoing'), ('CM', 'Commercial '), ('CO', 'Complated')], max_length=2, null=True),
        ),
    ]
