# Generated by Django 3.2 on 2022-02-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_auto_20220208_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landowners', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('land_address', models.TextField(blank=True, null=True)),
                ('property_location', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('type_of_development', models.CharField(blank=True, max_length=255, null=True)),
                ('special_feature', models.TextField(blank=True, null=True)),
                ('landowners_requirements', models.TextField(blank=True, null=True)),
                ('facing', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
