# Generated by Django 3.2 on 2022-02-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='depth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
